### ISSUE TITLE
(bug) Ionic Android requestPermission throws "Cannot read property 'apply' of undefined"

### ISSUE THREAD

**Issue by AdanGMC** [EinfachHans/cordova-plugin-contacts-x#10]
# Bug Report

I Installed the plugin on my Ionic App, but after importing the ContactsX from the module 'cordova-plugin-contacts-x', im trying to call the requestPermission() function but it throws me the next error: 
![issue](https://user-images.githubusercontent.com/6548531/110907162-9cc79280-82d2-11eb-8b2d-a5743a6f3c7d.png)

It doesn't appear to be related to the plugin itself, but I cant find the answer. 

Any help will be appreciated.

**Environment information:**
- Node version = 10.19.0
- Ionic CLI version = 6.11.9
- Cordova CLI version = 10.0.0
- Cordova platform version = android 9.0.0

**Comment by EinfachHans** [comment]
Please postpone the Output of `ionic cordova plugin list`

**Comment by AdanGMC** [comment]
In order to install the plugin, I ran the command shown on npmjs page  ("npm i cordova-plugin-contacts-x") but now that you mention it, the plugin is not listed in cordova list. It is normal?  

> cordova.cmd plugin ls
call-number 0.0.2 "Cordova Call Number Plugin"
com-sarriaroman-photoviewer 1.2.4 "PhotoViewer"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-androidx 3.0.0 "cordova-plugin-androidx"
cordova-plugin-app-version 0.1.12 "AppVersion"
cordova-plugin-camera 4.1.0 "Camera"
cordova-plugin-contacts 3.0.2-dev "Contacts"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-email-composer 0.8.15 "EmailComposer"
cordova-plugin-file-opener2 3.0.2 "File Opener2"
cordova-plugin-file-transfer 2.0.0-dev "File Transfer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-hms-push 5.0.2 "Cordova Plugin HMS Push"
cordova-plugin-inappbrowser 4.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"    
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"      
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-safariviewcontroller 1.6.0 "SafariViewController"       
cordova-plugin-splashscreen 6.0.0 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.8 "SocialSharing"
cordova-sqlite-storage 5.1.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"        
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.11.2 "OneSignal Push Notifications"
phonegap-plugin-barcodescanner 7.1.2 "BarcodeScanner"

**Comment by EinfachHans** [comment]
You don't install Plugins via **npm install** - you do via `ionic cordova plugin add`

**Comment by AdanGMC** [comment]
You are right. It works now!. Sorry, it was my bad. I just follow the instructions on the npmjs page, but I didnt install the plugin in the right way. Thanks!
