### ISSUE TITLE
(feat): To load photos?

### ISSUE THREAD

**Issue by charlieshin** [EinfachHans/cordova-plugin-contacts-x#12]
# Feature request

Is it possible to load contact's photo?

**Comment by fdendorfer** [comment]
Hi, is there an update on this?

**Comment by charlieshin** [comment]
Nope, I still cannot find how to show the contacts option from the iOS.  :-(
Do you need to set special values for cordova-plugin-add-swift-support?

**Comment by fdendorfer** [comment]
Unfortunately I'm very unfamiliar with mobile dev, but it seems the most likely problem could be a missing key `keysToFetch`

**Comment by charlieshin** [comment]
Sorry, I gave a wrong answer, the photos can be imported form Android and iOS, however, iOS meets another issue (since iOS 14) as what I reported that "Allow to access contacts" button in system perference and my App cannot read contacts anymore.  Don't know why yet but author seems has no such problem.

**Comment by EinfachHans** [comment]
There is an active PR for that: #14 but this is not finished yet. i don't have time for that myself sadly
