### ISSUE TITLE
(bug): contact access permission cannot be seen in iPhone settings/app own permission

### ISSUE THREAD

**Issue by charlieshin** [EinfachHans/cordova-plugin-contacts-x#16]
There is a serious problem for iOS platform 6.2.

The access contact permission cannot be seen from iPhone settings of app itself.  It means user has no way to turn it on allowing App to read contact.  However, platform 6.1.2 seems ok.

I try keep both corodva-plugin-contacts and cordova-plugin-contacts-x installed and now the access permission can be seen from in iPhone's setting page.

Please help.

**Comment by EinfachHans** [comment]
Please describe the Problem more detailed.

**Comment by charlieshin** [comment]
platform 6.2
install plugin-cordova-contacts-x
There is no contact permission access allow to change as attached picture.

platform 6.1.2
install plugin-cordova-contacts-x
There is no contact permission access allow to change as attached picture.

platform 6.1.2
install plugin-cordova-contacts-x
install plugin-cordova-contacts
The permission access allow to change.

platform 6.2
install plugin-cordova-contacts-x
install plugin-cordova-contacts
There is no contact permission access allow to change as attached picture.

![Screenshot 2021-09-14 at 23 58 28](https://user-images.githubusercontent.com/1762262/133293040-02a938fb-dee1-4adf-9de7-5a7c274064fd.png)

**Comment by EinfachHans** [comment]
I guess this is shown after the first `requestPermission`?

**Comment by charlieshin** [comment]
Yes, it showed after I start accessing contacts with the following condition.

platform 6.1.2
install plugin-cordova-contacts-x
install plugin-cordova-contacts
The permission access allow to change.

**Comment by charlieshin** [comment]
Hi, Is my description clear, or need more information?

**Comment by EinfachHans** [comment]
I can not reproduce this. I'm using `cordova-ios@6.2.0` and the setting is there. Other question, why are you installing both contacts Plugins?

**Comment by charlieshin** [comment]
Would you please try to remove your app first then install it again? Our iOS version is 14.8.
We don't want to install two plugins, just for testing purposes.

Thanks for your help.

**Comment by EinfachHans** [comment]
Then test the Plugin in a new App, i know it works.
