### ISSUE TITLE
(bug): App runs fine on device from CLI, but crashes upon launch if installed from PlayStore.

### ISSUE THREAD

**Issue by noe2505** [EinfachHans/cordova-plugin-contacts-x#23]
# Bug Report

**Current Behavior:**
App runs fine on device from CLI, but crashes upon launch if installed from PlayStore.

**Expected Behavior:**
App should run fine if downloaded from PlayStore.

**Steps to reproduce:**
cordova run android = runs fine
Download from PlayStore = crash.

**Screenshots:**
Not aplicable.

**Environment information:**
- Cordova CLI version 
	11.0.0
- Cordova platform version

  android 10.1.1
  browser 6.0.0
  ios 6.2.0

- Plugins & versions installed in project (including this plugin)

cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-android-notification-manager 0.0.1 "Notification Manager"
cordova-plugin-androidx-adapter 1.1.3 "cordova-plugin-androidx-adapter"
cordova-plugin-app-version 0.1.12 "AppVersion"
cordova-plugin-camera-with-exif 1.4.3 "cordova-plugin-camera-with-exif"
cordova-plugin-contacts-x 2.0.3 "ContactsX"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-geolocation 4.1.0 "Geolocation"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-media 5.0.4 "Media"
cordova-plugin-network-information 3.0.0 "Network Information"
cordova-plugin-push-notifications 1.0.1 "cordova-plugin-push-notifications"
cordova-plugin-statusbar 3.0.0 "StatusBar"
cordova-universal-links-plugin 1.2.1 "Universal Links Plugin"
cordova.plugins.diagnostic 6.1.1 "Diagnostic"

- Dev machine OS and version, e.g.
    - OSX
        - 12.0.1

**Additional information**

**config.xml permissions manifest:**

        <config-file target="AndroidManifest.xml" parent="/*">
            <uses-permission android:name="android.permission.INTERNET"/>
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
            <uses-permission android:name="android.permission.CAMERA" />
            <uses-permission android:name="android.permission.READ_CONTACTS" />
            <uses-permission android:name="android.permission.WRITE_CONTACTS" />
            <uses-permission android:name="android.permission.RECORD_AUDIO" />
            <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
            <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
            <uses-feature android:name="android.hardware.camera" />
            <uses-feature android:name="android.hardware.camera.autofocus" />
        </config-file>

**adb catlog:**

03-01 17:15:36.141 12367 13242 D OpenGLRenderer: RenderThread::setGrContext()
03-01 17:15:36.141 12367 12367 D AndroidRuntime: Shutting down VM
03-01 17:15:36.141 12367 12367 E AndroidRuntime: FATAL EXCEPTION: main
03-01 17:15:36.141 12367 12367 E AndroidRuntime: Process: tld.app, PID: 12367
03-01 17:15:36.141 12367 12367 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{tld.app/tld.app.MainActivity}: java.lang.RuntimeException: Failed to create webview. 
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4031)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4197)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2434)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8633)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: Caused by: java.lang.RuntimeException: Failed to create webview. 
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at e.a.a.u.C(Unknown Source:51)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at e.a.a.g.Q(Unknown Source:2)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at e.a.a.g.P(Unknown Source:2)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at e.a.a.g.s(Unknown Source:0)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at e.a.a.g.N(Unknown Source:4)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at tld.app.MainActivity.onCreate(Unknown Source:28)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8282)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8262)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1335)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4005)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	... 12 more
03-01 17:15:36.141 12367 12367 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: e.a.a.e0.f.<init> [class android.content.Context, class e.a.a.q]
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at java.lang.Class.getConstructor0(Class.java:2363)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at java.lang.Class.getConstructor(Class.java:1759)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	at e.a.a.u.C(Unknown Source:29)
03-01 17:15:36.141 12367 12367 E AndroidRuntime: 	... 21 more

**Comment by noe2505** [comment]
On further testing, I created a blank project with no other plugins or platforms:


cordova plugin ls:

cordova-plugin-contacts-x 2.0.3 "ContactsX"


cordova platform ls:

Installed platforms:
  android 10.1.1
Available platforms: 
  browser ^6.0.0
  electron ^3.0.0
  ios ^6.2.0
  osx ^6.0.0


Created a release apk and installed it into device with adb install, same result: app crashes upon launch.


Edit:

Version 2.0.3 seems to work OK, albeit losing the improvements present in the latest plugin version, but hey, working is better than not working, i guess.

**cordova plugin add cordova-plugin-contacts-x@2.0.3**

**Comment by YannickDa** [comment]
Hello,

Same here. Same catlog error with the "Failed to create webview" with the last version.

It's working well on iOS but not on Android.

With the 2.0.3 version, everything works well.

**Comment by spoxies** [comment]
I have ~no~ some clue why (for now) but please change the following in lines `cordova-plugin-contacts-x/src/android/build.gradle`
```gradle

 release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
```
to 

```gradle

 release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

```

~Currently looking at a reliable implementation of bellow sources~, it is a known issue 
https://github.com/MichaelRocks/libphonenumber-android/blob/master/sample/proguard-rules.pro
https://stackoverflow.com/questions/27310268/how-to-use-proguard-in-cordova-android-app

There does not seem to be a reliable/eloquent way to handle this from within a cordova plugin.
I just happen to see this issue by chance and in my initial release/tests it did not appear. 

It was also me who introduced this bug in the `cordova-plugin-contacts-x` plugin so sorry for this.

**Comment by EinfachHans** [comment]
Your fix is added in the [last Version](https://github.com/EinfachHans/cordova-plugin-contacts-x/releases/tag/V2.1.1) - Please check this out :)

**Comment by noe2505** [comment]
That is not really a fix tho, it just skips optimizations provided by Proguard. Real fix would be for this to work without disabling it, like most other plugins out there.

**Comment by EinfachHans** [comment]
> That is not really a fix tho, it just skips optimizations provided by Proguard. Real fix would be for this to work without disabling it, like most other plugins out there.

@spoxies

**Comment by spoxies** [comment]
@noe2505 Thanks for your opinion. 

As said:
> @spoxies : There does not seem to be a reliable/eloquent way to handle this from within a cordova plugin.

The proguard file needs to be (reliably) updated with the cordova package/app name in which you state to exclude classmembers. There might be a way (and please share what you know or open a PR). However the urgency/impact of this bug was such that a less optimised library is better than the bug it caused. Hence this was pushed as a hotfix.

If you have technical reference or other cordova plugin repo where this is handled reliable using libphonenumber. I'll be very happy to adjust and would safe further time/research.

**Comment by spoxies** [comment]
My suggestion would be that if one wants to make use of proguard, one should take a look at [cordova-plugin-proguard](https://github.com/greybax/cordova-plugin-proguard) This way a developer can decide for its own if it likes to enable/use proguard and more importantly adjust/configure it as needed. This seems to be the common practise at the moment (as far as I can tell).  

I took the [suggestion](https://github.com/google/libphonenumber/wiki/Android-Studio-setup) from the libphonenumber documentation. But I conclude that enabling proguard was uninformed and optimistic on my side. It is not very compatible with Cordova (even glitchy as it did not occur in my release test), and enabling it should probably not be decided by the plugin. 

E.g. if you are using the widely used 'cordova-plugin-googlemaps' you would also have to put in additional exclude rules with your app name in there. (https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/593, https://alfilatov.com/posts/how-to-setup-proguard-in-cordova-application/) So having proguard enabled in the gradle build file seems to make the plugin less opaque, less reliable and less compatible. 

Currently the proguard files are still generated but they might be removed entirely, or could be commented with some additional instructions in the build.gradle explaining what to enable/configure if one would like to use proguard. I'm not aware of 'most other plugins' that do use proguard @noe2505
