### ISSUE TITLE
(bug): Error updating plugin version 2.0.3 -> 2.1.0

### ISSUE THREAD

**Issue by neverWinters** [EinfachHans/cordova-plugin-contacts-x#24]
Hi, we are having a problem updating the plugin at the application level, we are currently using version 2.0.3 but we want to migrate to version 2.1.0 as the most updated. The steps to update using cordova prepare are followed but the download of the correct version is not achieved, it continues to show version 2.0.3. Here is the evidence of the error. 

**Current Behavior:**
"cordova plugin add cordova-plugin-contacts-x" command install plugin version 2.0.3
"cordova plugin add cordova-plugin-contacts-x@2.1.0" command install plugin version 2.0.3
"cordova plugin add https://github.com/EinfachHans/cordova-plugin-contacts-x" command install plugin version 2.0.3

**Expected Behavior:**
"cordova plugin add cordova-plugin-contacts-x" command install plugin version 2.1.0
"cordova plugin add cordova-plugin-contacts-x@2.1.0" command install plugin version  2.1.0
"cordova plugin add https://github.com/EinfachHans/cordova-plugin-contacts-x" command install plugin version  2.1.0

**Steps to reproduce:**
Create a new cordova proyect with the command "cordova create myApp"
Add plugin with the comman "cordova plugin add cordova-plugin-contacts-x"
Validate plugin version

**Environment information:**

- Cordova CLI version 
	- 9.0.0
	- 10.0.0
	- 11.0.0
- Cordova platform version
	- New project, no platforms
- Plugins & versions installed in project (including this plugin)
    - New project, no more plugins
- Dev machine OS and version, e.g.
    - OSX
        - Big Sur 11.6.4

**Comment by EinfachHans** [comment]
See #23
