### ISSUE TITLE
scope not access inside function results to find contacts (bug):

### ISSUE THREAD

**Issue by jmosqueda1987** [EinfachHans/cordova-plugin-contacts-x#29]
Hi, we recently use this plugins to replace de official plugin of ionic, but I have a little problem, When I use the "find" method i didn´t access to "this" scope inside the callback function, can you help me to resolve this please. I currently use ionic with Angular.

Regards

**Comment by EinfachHans** [comment]
I would suggest creating a Service that wraps the plugin and map it to a Promise, for example like:

```ts
public findContacts(options: FindOptions): Promise<ContactX[]> {
    return new Promise<ContactX[]>((resolve, reject) => {
      ContactsX.find(result => {
        resolve(result);
      }, error => {
        reject(error);
      }, options
      );
    });
  }
```

Then use this Service/Function
