### ISSUE TITLE
need edit ,add and remove contact functionality in this plugin 

### ISSUE THREAD

**Issue by yashp98** [EinfachHans/cordova-plugin-contacts-x#3]
# Feature request

- we can able to add new contact.
- we can able to edit existing contact.
-we can able to remove contact

**Comment by EinfachHans** [comment]
I'm currently really busy but this will definitely be done in the future. Is planned for next Version.

**Comment by EinfachHans** [comment]
update: i implemented android today (not released yet). iOS will follow, but will take some longer

**Comment by yashp98** [comment]
ok thanks for your time

**Comment by EinfachHans** [comment]
[Version 2.0.0](https://github.com/EinfachHans/cordova-plugin-contacts-x/blob/master/CHANGELOG.md#200) released 😊 To be honest i did only a minimum of testing so pls let me know if anything works different from what you are expecting
