### ISSUE TITLE
(bug): Gradle compile() configuration is now obsolete

### ISSUE THREAD

**Issue by cmateustechy** [EinfachHans/cordova-plugin-contacts-x#32]
[Removal of compile and runtime configurations](https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal)
Since its inception, Gradle provided the compile and runtime configurations to declare dependencies. These however did not support a fine grained scoping of dependencies. Hence, better replacements were introduced in Gradle 3.4:

The implementation configuration should be used to declare dependencies which are implementation details of a library: they are not visible to consumers of the library during compilation time.

The api configuration, available only if you apply the java-library plugin, should be used to declare dependencies which are part of the API of a library, that need to be exposed to consumers at compilation time.

[Gradle](https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal)

Need change this setup

dependencies {
    **_compile_** 'com.googlecode.libphonenumber:libphonenumber:8.2.0'
}

**Comment by EinfachHans** [comment]
should be fixed by #31
