### ISSUE TITLE
(feat): phoneNumbers type (mobile, home, work, ...)

### ISSUE THREAD

**Issue by mst2020** [EinfachHans/cordova-plugin-contacts-x#4]
Hello Hans,

right now i'm integrating your nice little plugin, is there any chance to add the phoneNumbers type?

Like you do with the Emails?

https://developer.android.com/reference/android/provider/ContactsContract.CommonDataKinds.Phone

Thanks

**Comment by EinfachHans** [comment]
i already implemented this for android, ios is a todo yet. Will release this together with #3 in next major version

**Comment by mst2020** [comment]
Nice, many thanks for the fast response! :)

**Comment by EinfachHans** [comment]
added in 2.0.0 - pls go ahead and test

**Comment by mst2020** [comment]
@EinfachHans Works perfectly.. Thanks! 👍

I'm using the "pick" method:
`"phoneNumbers":[{"id":"131","value":"+49 000 00000000","type":"mobile"}]`

Tested with:
```
cordova-android 9.0.0
cordova-plugin-contacts-x: 2.0.0
Android 8.0.0
```
