### ISSUE TITLE
(feat): How to work is Ionic

### ISSUE THREAD

**Issue by mebinvarghese** [EinfachHans/cordova-plugin-contacts-x#5]
# How plugin work in ionic 4 or above

Could you please share, how it working in ionic 4 or greater

**Comment by EinfachHans** [comment]
Read the **Usage** part in the read.me...

**Comment by mebinvarghese** [comment]
But `window.ContactsX` is showing undefined error

**Comment by EinfachHans** [comment]
Please try the typescript definition

**Comment by mebinvarghese** [comment]
Could you please share your mail id or please sent a mail to mebinvarghese007@gmail.com for some help

**Comment by mebinvarghese** [comment]
Thanks for your reply

**Comment by EinfachHans** [comment]
no, github is the place for this, have you tested the ts definition?

also pls post the output of `ionic cordova plugin list`

**Comment by mebinvarghese** [comment]
> cordova plugin ls
```
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-contacts-x 1.1.0 "ContactsX"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Comment by mebinvarghese** [comment]
I don't know how to use ts definition, could you please give me an example please?

**Comment by EinfachHans** [comment]
I can't help you if you don't read the read.me - it's explained there!

**Comment by mebinvarghese** [comment]
`import ContactsX from 'cordova-plugin-contacts-x';
`
lemme try with this methode and get back to here

**Comment by mebinvarghese** [comment]
Thanks for your time
