### ISSUE TITLE
Support Question: ContactX.firstName is null; iOS

### ISSUE THREAD

**Issue by Sunny41** [EinfachHans/cordova-plugin-contacts-x#8]
Hi there, it's me again. 
I hope I'm not stupid again :D 

It's working fine and the object return on ContactX.pick() looks fine too. 
But when I want to do this: 
`this.name = contactX.firstName`
the compiler shows this error: 
`null is not an object (evaluating this.name = contactX.firstName)`
if I do a console.log, contactX.firstName is showing correctly... 

Thanks for helping again!

**Comment by EinfachHans** [comment]
Please post the full code which is related to this including the pick method and stuff

**Comment by Sunny41** [comment]
`import ContactsX from 'cordova-plugin-contacts-x'`
...
```  addFromContacts() {

    ContactsX.requestPermission(function (success) {

      ContactsX.pick(function (contact) {

        console.log(success);

        console.log(contact);

        console.log(contact.firstName);

        const contactInfo = contact;

        console.log(contactInfo);

        this.name = contactInfo.firstName;

        ...

      }, function (error) {

        console.log(error);

      });

    }, function (error) {

      console.log(error);

    });

  }```

**Comment by EinfachHans** [comment]
So the error happens here: `this.name = contactInfo.firstName;`?

But the line before is printing the contact correctly with `firstName`?

**Comment by Sunny41** [comment]
exactly :) 
I tried to do that without using a new variable and the same error occurs... 
tried that with ios 12 on an iphone 5 and with the simulator of an iphone 12 with ios 14

**Comment by EinfachHans** [comment]
That doesn't make sense 🤯 pls create a small reproducable repo

**Comment by Sunny41** [comment]
i created one here : https://github.com/Sunny41/contactsx-example 
it has a simple button on the homepage and the same code I posted above in the chooseContact() method :)

**Comment by Sunny41** [comment]
Hi there again, 
I tested it on the android emulator with pixel XL and  on my physical device samsung galaxy s10 with android 11. 

`cordova.js:314 Uncaught TypeError: Cannot set property 'name' of null
    at main.js:6755
    at Object.callbackFromNative (cordova.js:295)
    at <anonymous>:1:9`

**Comment by EinfachHans** [comment]
Hey there. Sorry for the late response.

I just checkout your Repo. The problem is not that `firstName` is null, the problem is that there is no variable `name`, so `this.name` can't work.

And even if there was a class variable called **name** it may not work. Please read this: https://logicmason.com/2019/how-to-access-this-from-inside-a-callback/
